Repository mariokreitz/JOIN, pull requests merged in 2024-10, with the labels that each got.

#17 Contact page changes
  assets/styles/contactView.css
  scripts/contactModal.js
  scripts/contactView.js
  scripts/services/apiService.js
  scripts/templates/contactModal.template.js
  scripts/templates/contactView.template.js
Labels: question

#56 docs: add badges for project status and metadata
  README.md
Labels: documentation

#55 Update SECURITY.md
  SECURITY.md
Labels: documentation

#54 Refactor: Update Functions, Fix Logic Issues, and Improve Documentation
  assets/styles/bigCard-modal-edit.css
  assets/styles/bigCard-modal.css
  scripts/addTaskGlobals.js
  scripts/board.js
  scripts/contactModal.js
  scripts/contactView.js
  scripts/contacts.js
  scripts/helper/taskcard.helper.js
  scripts/services/apiService.js
  scripts/templates/contactsList.template.js
  scripts/templates/taskCardBig.template.js
  scripts/templates/taskCardBigEdit.template.js
  scripts/templates/taskCardSmall.template.js
  scripts/toastMessage.js
Labels: bug, documentation, enhancement

#57 feat: add mobile-friendly menu for changing todo state
  assets/styles/task-card-small.css
  scripts/board.js
  scripts/helper/taskcard.helper.js
  scripts/templates/taskCardSmall.template.js
Labels: enhancement

#58 Board small todo card fix
  scripts/board.js
  scripts/helper/taskcard.helper.js
  scripts/templates/taskCardSmall.template.js
Labels: enhancement

#59 Add-Task responsiveness and general UI/UX improvements
  add-task.html
  assets/styles/addTask.css
  assets/styles/addTaskModal.css
  assets/styles/bigCard-modal-edit.css
  assets/styles/contacts.css
  assets/styles/help.css
  assets/styles/legal-notice.css
  assets/styles/toastMessage.css
  assets/svg/board-icon.svg
  scripts/addTask.js
  scripts/addTaskGlobals.js
  scripts/addTaskModal.js
  scripts/templates/addTask.template.js
  scripts/templates/contactlistDropdown.template.js
  scripts/templates/subtaskListItem.js
  scripts/toastMessage.js
  style.css
Labels: enhancement

#60 Board mc
  add-task.html
  assets/styles/addTask.css
  assets/styles/bigCard-modal-edit.css
  assets/styles/bigCard-modal.css
  assets/styles/bigCardModalEditNew.css
  assets/styles/toastMessage.css
  board.html
  scripts/addTask.js
  scripts/addTaskModal.js
  scripts/bigcard-modal-edit.js
  scripts/board.js
  scripts/contactDropDown.js
  scripts/helper/taskcard.helper.js
  scripts/subtask.js
  scripts/templates/taskCardBig.template.js
  scripts/templates/taskCardBigEdit.template.js
  scripts/toastMessage.js
  scripts/utility.js
Labels: bug, enhancement

#62 docs: update README with new badges and repositioning
  README.md
Labels: documentation

#66 Board fix patch
  assets/styles/task-card-small.css
  scripts/addTask.js
Labels: enhancement
